---
abstract: 'Release tests for kwalitee'
author:
  - 'Harley Pig <harleypig@gmail.com>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-Kwalitee
provides:
  Dist::Zilla::Plugin::Test::Kwalitee:
    file: lib/Dist/Zilla/Plugin/Test/Kwalitee.pm
    version: 1.112390
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Test::Kwalitee: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Test-Kwalitee
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Test-Kwalitee/
  repository: git://github.com/harleypig/Dist-Zilla-Plugin-Test-Kwalitee.git
version: 1.112390
