---
abstract: 'Release tests for kwalitee'
author:
  - 'Harley Pig <harleypig@gmail.com>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Carp: 0
  Dist::Zilla::Tester: 0
  File::Path: 2.07
  Path::Class: 0
  Scalar::Util: 0
  Test::More: 0.94
  blib: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-Kwalitee
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - DB
requires:
  Data::Section: 0.004
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::PrereqSource: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Sub::Exporter::ForMethods: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Test-Kwalitee
  homepage: https://metacpan.org/release/Dist-Zilla-Plugin-Test-Kwalitee
  repository: git://github.com/karenetheridge/Dist-Zilla-Plugin-Test-Kwalitee.git
version: 2.06
x_authority: cpan:MARCEL
