use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Harley
Pig
harleypig
Caleb
Cushing
xenoterracide
Marcel
Gruenauer
marcel
Kent
Fredric
kentfredric
Karen
Etheridge
ether
hanekomu
Mike
Doherty
doherty
Graham
Knop
haarg
lib
Dist
Zilla
Plugin
Test
Kwalitee
